server.port: 8081

resilience4j.ratelimiter:
  instances:
    cryptoRateLimiter:
      limitForPeriod: 2
      limitRefreshPeriod: 10s
      timeoutDuration: 1s

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/crypto?reconnect=true&useUnicode=true&characterEncoding=UTF-8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
  application:
    name: crypto-service
  jpa:
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: UTC